import LoadingSkeleton from '../LoadingSkeleton';
import AdminReprocessPanel from './AdminReprocessPanel';
import AdminLlmVisibilitySettings from './AdminLlmVisibilitySettings';
import AdminFirmHealthTable from './AdminFirmHealthTable';
import { AdminSummaryCards, AdminSystemStatus, AdminArchiveHistory, AdminFirmRecords, AdminLogBrowser } from './AdminConsoleSections';

export default function AdminConsoleContent({ user, refreshIntervalMs, refreshOptions, onRefreshChange, onRefresh, statusLoading, statusError, summary, systemStatus, archiveHistory, firmRecords, firmHealth, processing, logLines, onReprocess, onClearLog, llmVisibility, updatingLlm, llmFeedback, onLlmChange, logBrowser, logViewer, onDir, onFile, onRoot, viewerRef }) {
  return <div className="admin-console container"><h1>🛠️ 관리자 콘솔</h1><p className="subtitle">{user.first_name || user.username} 님, 환영합니다 · {new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' })}</p><div className="refresh-bar"><button className="refresh-btn" onClick={onRefresh} disabled={statusLoading}>↻ {statusLoading ? '갱신 중...' : '새로고침'}</button><span className="refresh-label">자동 갱신:</span><div className="refresh-interval-group">{refreshOptions.map((option) => <button key={option.value} className={`refresh-interval-btn ${refreshIntervalMs === option.value ? 'active' : ''}`} onClick={() => onRefreshChange(option.value)}>{option.label}</button>)}</div></div><AdminSummaryCards summary={summary} /><AdminSystemStatus systemStatus={systemStatus} loading={statusLoading} error={statusError} /><AdminArchiveHistory archiveHistory={archiveHistory} /><AdminFirmRecords records={firmRecords} /><AdminLlmVisibilitySettings llmVisibility={llmVisibility} updatingLlm={updatingLlm} feedback={llmFeedback} onChange={onLlmChange} /><div className="section-card"><div className="section-title">🩺 증권사 건강검진</div>{firmHealth ? <AdminFirmHealthTable firmHealth={firmHealth} /> : <LoadingSkeleton rows={4} label="증권사 상태 불러오는 중" />}</div><AdminReprocessPanel processing={processing} logLines={logLines} onReprocess={onReprocess} onClearLog={onClearLog} /><AdminLogBrowser browser={logBrowser} viewer={logViewer} onDir={onDir} onFile={onFile} onRoot={onRoot} viewerRef={viewerRef} /></div>;
}
