import { createPortal } from 'react-dom';
import HamburgerMenu from '../HamburgerMenu';
import KeywordOverlay from '../menu/KeywordOverlay';
import { AccountPopover, BellIcon, NotificationPopover } from '../HeaderPopovers';

export default function HeaderLayout({ refProp, hidden, onHome, badge, onSearch, user, onNotifications, active, unread, menuOpen, toggleMenu, closePopover, keywordState, authLoading, login, notifications, loading, readIds, markAll, onNotification, toast, setActive, logout, selectedCompany, companyChange, headerClick, boards, selectedBoard, boardChange, onOpenSettings, theme, themePreference, onToggleTheme }) {
  return <>
    <header ref={refProp} className={hidden ? 'nav-hidden' : ''}><div className="header-top"><div className="title" onClick={onHome}>🏠 ssh-reports-hub</div><div className="header-actions">{badge}<button type="button" className="header-search-button" onClick={onSearch} title="검색" aria-label="검색 열기"><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></button>{user && <button type="button" className="header-notification-button" onClick={onNotifications} title="리포트 알림" aria-label="리포트 알림" aria-expanded={active === 'notifications'} aria-haspopup="dialog"><BellIcon />{unread > 0 && <span className="notification-badge">{unread}</span>}</button>}<button type="button" className="hamburger-menu" onClick={toggleMenu} title="메뉴" aria-label="메뉴 열기"><div /><div /><div /></button></div></div></header>
    {active === 'notifications' && user && <NotificationPopover telegramUser={user} keywords={keywordState.keywords} isLoadingKeywords={keywordState.isLoadingKeywords} onClose={closePopover} onOpenSettings={onOpenSettings} onLogin={login} isAuthenticating={authLoading} notifications={notifications} isLoadingNotifications={loading} readNotifyIds={readIds} onMarkAllAsRead={markAll} onNotificationClick={onNotification} />}
    {toast && user && <button type="button" className="header-notification-toast" onClick={() => { setActive('notifications'); }}><span className={`notification-toast-icon ${toast.source || 'summary'}`}>{toast.source === 'telegram' ? 'T' : '▲'}</span><span>{toast.message}</span></button>}
    {active === 'account' && <AccountPopover telegramUser={user} onClose={closePopover} onOpenSettings={onOpenSettings} onLogout={logout} theme={theme} themePreference={themePreference} onToggleTheme={onToggleTheme} />}
    <HamburgerMenu isOpen={menuOpen} toggleMenu={toggleMenu} selectedCompany={selectedCompany} handleCompanyChange={companyChange} handleHeaderClick={headerClick} boards={boards} selectedBoard={selectedBoard} handleBoardChange={boardChange} />
    {keywordState.isKeywordOverlayOpen && createPortal(<KeywordOverlay newKeyword={keywordState.newKeyword} setNewKeyword={keywordState.setNewKeyword} handleAddKeyword={keywordState.handleAddKeyword} handleDeleteKeyword={keywordState.handleDeleteKeyword} handleDeleteAllKeywords={keywordState.handleDeleteAllKeywords} handleUndoDelete={keywordState.handleUndoDelete} keywords={keywordState.keywords} isLoadingKeywords={keywordState.isLoadingKeywords} lastDeleted={keywordState.lastDeleted} toggleKeywordOverlay={keywordState.closeKeywordOverlay} />, document.body)}
  </>;
}
