import MenuSummary from '../MenuSummary';
import FnGuideSummaryCard from './FnGuideSummaryCard';
import { DateChips, Facets } from './FnGuideControls';
import { REPORT_SECTIONS } from '../../constants/reportSections';

function SummaryGroups({ groups, selectedId, expanded, collapsed, visible, onNavigate, onToggle, onToggleGroup }) {
  return groups.map((dateGroup) => <section className="fnguide-date-section" key={dateGroup.date}><div className="fnguide-date-heading"><h2>{dateGroup.date}</h2><span>{dateGroup.reportCount}건</span></div>{dateGroup.repeated.length > 0 && <div className="fnguide-repeated-area"><div className="fnguide-repeated-title">집중 발간 종목</div>{dateGroup.repeated.map((company) => { const key = `${dateGroup.date}-${company.key}`; const isCollapsed = collapsed[key]; return <section className="fnguide-company-group" key={key}><button type="button" className="fnguide-company-group-toggle" onClick={() => onToggleGroup(key)} aria-expanded={!isCollapsed}><span className="company-group-main"><strong>{company.companyName}</strong>{company.companyCode && <small>{company.companyCode}</small>}</span><span className="company-group-meta"><span className="company-report-count">{company.items.length}건</span><small>{[...new Set(company.items.map((item) => item.provider).filter(Boolean))].join(' · ')}</small><span aria-hidden="true">{isCollapsed ? '＋' : '−'}</span></span></button>{!isCollapsed && <div className="fnguide-company-reports">{company.items.map((item) => <FnGuideSummaryCard key={item.summary_id} item={item} showCompany={false} isSelected={String(item.summary_id) === selectedId} isExpanded={expanded[item.summary_id]} selectedIndex={visible.findIndex((summary) => String(summary.summary_id) === String(item.summary_id))} visibleSummaries={visible} onNavigate={onNavigate} onToggleExpand={onToggle} />)}</div>}</section>;})}</div>}{dateGroup.singles.length > 0 && <div className="fnguide-single-reports">{dateGroup.singles.map((company) => { const item = company.items[0]; return <FnGuideSummaryCard key={item.summary_id} item={item} showCompany isSelected={String(item.summary_id) === selectedId} isExpanded={expanded[item.summary_id]} selectedIndex={visible.findIndex((summary) => String(summary.summary_id) === String(item.summary_id))} visibleSummaries={visible} onNavigate={onNavigate} onToggleExpand={onToggle} />; })}</div>}</section>);
}

export default function FnGuideListContent({ selectedDate, searchQuery, providerFilter, dates, datesLoading, datesError, onRetryDates, onDateSelect, onScrollDates, chipsRef, facets, facetType, selectedFacet, onFacetType, onFacetValue, onFacetReset, filteredSummaries, groups, visibleSummaries, selectedSummaryId, expandedItems, collapsedGroups, onNavigate, onToggleExpand, onToggleGroup, summariesError, isLoading, hasMore, onLoadMore, onSubmitSearch, onSearchChange, onProviderChange }) {
  return <div className="fnguide-container"><div className="fnguide-header-panel"><MenuSummary menuName={REPORT_SECTIONS.fnguide.title} description={REPORT_SECTIONS.fnguide.description} summaryItems={[{ label: '조회일', value: selectedDate || '전체', icon: '📅' }, { label: '레포트', value: filteredSummaries.length, icon: '📄' }, ...(searchQuery ? [{ label: '검색', value: searchQuery, icon: '🔍' }] : []), ...(providerFilter ? [{ label: '증권사', value: providerFilter, icon: '🏢' }] : [])]} />{!selectedDate && <form className="fnguide-search-form" onSubmit={onSubmitSearch}><div className="search-input-wrapper"><span className="search-icon">🔍</span><input className="fnguide-search-input" placeholder="회사명, 제목, 요약 내용 검색..." value={searchQuery} onChange={onSearchChange} />{searchQuery && <button type="button" className="clear-search-btn" onClick={() => onSearchChange({ target: { value: '' } })}>✕</button>}</div><input className="fnguide-provider-input" placeholder="증권사 필터..." value={providerFilter} onChange={onProviderChange} /><button type="submit" className="fnguide-search-submit">검색</button></form>}<DateChips dates={dates} selectedDate={selectedDate} loading={datesLoading} error={datesError} onSelect={onDateSelect} onScroll={onScrollDates} chipsRef={chipsRef} retry={onRetryDates} />{filteredSummaries.length > 0 && <Facets facets={facets} facetType={facetType} selectedFacet={selectedFacet} maxCount={facets[facetType]?.[0]?.count || 0} onType={onFacetType} onValue={onFacetValue} onReset={onFacetReset} />}</div><div className="fnguide-list">{summariesError && !filteredSummaries.length ? <AsyncErrorState message="FnGuide 요약 레포트를 불러오지 못했습니다." onRetry={onRetryDates} /> : !filteredSummaries.length && !isLoading ? <div className="no-data-msg">검색 조건에 부합하는 요약 레포트가 없습니다.</div> : <SummaryGroups groups={groups} selectedId={selectedSummaryId} expanded={expandedItems} collapsed={collapsedGroups} visible={visibleSummaries} onNavigate={onNavigate} onToggle={onToggleExpand} onToggleGroup={onToggleGroup} />}</div>{isLoading && <LoadingSkeleton rows={6} label="FnGuide 요약 불러오는 중" />}{!isLoading && hasMore && filteredSummaries.length > 0 && <button className="load-more-btn" onClick={onLoadMore}>더보기</button>}</div>;
}
