import MenuSummary from '../MenuSummary';
import LoadingSkeleton from '../LoadingSkeleton';
import AsyncErrorState from '../AsyncErrorState';
import FnGuideSummaryGroups from './FnGuideSummaryGroups';
import { DateChips, Facets } from './FnGuideControls';
import { REPORT_SECTIONS } from '../../constants/reportSections';

export default function FnGuideListContent({ selectedDate, searchQuery, providerFilter, dates, datesLoading, datesError, onRetryDates, onDateSelect, onScrollDates, chipsRef, facets, facetType, selectedFacet, onFacetType, onFacetValue, onFacetReset, filteredSummaries, groups, visibleSummaries, selectedSummaryId, expandedItems, collapsedGroups, onNavigate, onToggleExpand, onToggleGroup, summariesError, isLoading, hasMore, onLoadMore, onSubmitSearch, onSearchChange, onProviderChange }) {
  return <div className="fnguide-container"><div className="fnguide-header-panel"><MenuSummary menuName={REPORT_SECTIONS.fnguide.title} description={REPORT_SECTIONS.fnguide.description} summaryItems={[{ label: '조회일', value: selectedDate || '전체', icon: '📅' }, { label: '레포트', value: filteredSummaries.length, icon: '📄' }, ...(searchQuery ? [{ label: '검색', value: searchQuery, icon: '🔍' }] : []), ...(providerFilter ? [{ label: '증권사', value: providerFilter, icon: '🏢' }] : [])]} />{!selectedDate && <form className="fnguide-search-form" onSubmit={onSubmitSearch}><div className="search-input-wrapper"><span className="search-icon">🔍</span><input className="fnguide-search-input" placeholder="회사명, 제목, 요약 내용 검색..." value={searchQuery} onChange={onSearchChange} />{searchQuery && <button type="button" className="clear-search-btn" onClick={() => onSearchChange({ target: { value: '' } })}>✕</button>}</div><input className="fnguide-provider-input" placeholder="증권사 필터..." value={providerFilter} onChange={onProviderChange} /><button type="submit" className="fnguide-search-submit">검색</button></form>}<DateChips dates={dates} selectedDate={selectedDate} loading={datesLoading} error={datesError} onSelect={onDateSelect} onScroll={onScrollDates} chipsRef={chipsRef} retry={onRetryDates} />{filteredSummaries.length > 0 && <Facets facets={facets} facetType={facetType} selectedFacet={selectedFacet} maxCount={facets[facetType]?.[0]?.count || 0} onType={onFacetType} onValue={onFacetValue} onReset={onFacetReset} />}</div><div className="fnguide-list">{summariesError && !filteredSummaries.length ? <AsyncErrorState message="FnGuide 요약 레포트를 불러오지 못했습니다." onRetry={onRetryDates} /> : !filteredSummaries.length && !isLoading ? <div className="no-data-msg">검색 조건에 부합하는 요약 레포트가 없습니다.</div> : <FnGuideSummaryGroups groups={groups} selectedId={selectedSummaryId} expanded={expandedItems} collapsed={collapsedGroups} visible={visibleSummaries} onNavigate={onNavigate} onToggle={onToggleExpand} onToggleGroup={onToggleGroup} />}</div>{isLoading && <LoadingSkeleton rows={6} label="FnGuide 요약 불러오는 중" />}{!isLoading && hasMore && filteredSummaries.length > 0 && <button className="load-more-btn" onClick={onLoadMore}>더보기</button>}</div>;
}
